import type { CommandEntry } from "../types";
import * as home from "../actions/home";
import { HIGHLIGHT_COLORS, highlightWithColor } from "../actions/highlight";

export const HOME_COMMANDS: CommandEntry[] = [
  { id: "bold", tab: "home", group: "Font", icon: "bold", label: "Bold", action: home.toggleBold },
  { id: "italic", tab: "home", group: "Font", icon: "italic", label: "Italic", action: home.toggleItalic },
  {
    id: "strikethrough",
    tab: "home",
    group: "Font",
    icon: "strikethrough",
    label: "Strikethrough",
    action: home.toggleStrikethrough,
  },
  {
    id: "highlight",
    tab: "home",
    group: "Font",
    icon: "highlighter",
    label: "Highlight",
    options: HIGHLIGHT_COLORS.map((color) => ({
      id: `highlight-${color.id}`,
      label: color.emoji ? `${color.emoji}  ${color.name}` : color.name,
      action: highlightWithColor(color.emoji),
    })),
  },
  { id: "inline-code", tab: "home", group: "Font", icon: "code", label: "Code", action: home.toggleInlineCode },
  {
    id: "underline",
    tab: "home",
    group: "Font",
    icon: "underline",
    label: "Underline",
    action: home.toggleUnderline,
  },
  {
    id: "superscript",
    tab: "home",
    group: "Font",
    icon: "superscript",
    label: "Superscript",
    action: home.toggleSuperscript,
  },
  {
    id: "subscript",
    tab: "home",
    group: "Font",
    icon: "subscript",
    label: "Subscript",
    action: home.toggleSubscript,
  },
  {
    id: "comment",
    tab: "home",
    group: "Font",
    icon: "eye-off",
    label: "Comment",
    action: home.toggleComment,
  },
  {
    id: "change-case",
    tab: "home",
    group: "Font",
    icon: "case-sensitive",
    label: "Change Case",
    options: [
      { id: "case-upper", label: "UPPERCASE", action: home.toUpperCase },
      { id: "case-lower", label: "lowercase", action: home.toLowerCase },
      { id: "case-title", label: "Title Case", action: home.toTitleCase },
      { id: "case-sentence", label: "Sentence case", action: home.toSentenceCase },
    ],
  },
  {
    id: "clear-formatting",
    tab: "home",
    group: "Font",
    icon: "eraser",
    label: "Clear Formatting",
    action: home.clearFormatting,
  },
  {
    id: "heading",
    tab: "home",
    group: "Paragraph",
    icon: "heading",
    label: "Heading",
    options: [
      { id: "heading-1", label: "Heading 1", action: home.setHeading(1) },
      { id: "heading-2", label: "Heading 2", action: home.setHeading(2) },
      { id: "heading-3", label: "Heading 3", action: home.setHeading(3) },
    ],
  },
  {
    id: "bullet-list",
    tab: "home",
    group: "Paragraph",
    icon: "list",
    label: "Bulleted List",
    action: home.toggleBulletList,
  },
  {
    id: "numbered-list",
    tab: "home",
    group: "Paragraph",
    icon: "list-ordered",
    label: "Numbered List",
    action: home.toggleNumberedList,
  },
  {
    id: "checklist",
    tab: "home",
    group: "Paragraph",
    icon: "list-checks",
    label: "Checklist",
    action: home.toggleChecklist,
  },
  {
    id: "blockquote",
    tab: "home",
    group: "Paragraph",
    icon: "quote",
    label: "Quote",
    action: home.toggleBlockquote,
  },
];
