import type { CommandEntry } from "../types";
import * as insertActions from "../actions/insert";
import * as tableEdit from "../actions/tableEdit";
import {
  DELETE_COLUMN_ICON,
  DELETE_ROW_ICON,
  INSERT_COLUMN_LEFT_ICON,
  INSERT_COLUMN_RIGHT_ICON,
  INSERT_ROW_ABOVE_ICON,
  INSERT_ROW_BELOW_ICON,
} from "../../iconIds";
import { openCallout, openExternalLink, openInternalLink, openEmbed } from "../modalLoaders";
import { SYMBOL_OPTIONS } from "../symbols";
import { CODE_LANGUAGES } from "../codeLanguages";

export const INSERT_COMMANDS: CommandEntry[] = [
  { id: "link", tab: "insert", group: "Links", icon: "link", label: "Link", modal: openExternalLink },
  {
    id: "internal-link",
    tab: "insert",
    group: "Links",
    icon: "file-symlink",
    label: "Internal Link",
    modal: openInternalLink,
  },
  { id: "tag", tab: "insert", group: "Links", icon: "tag", label: "Tag", action: insertActions.insertTag },
  { id: "image", tab: "insert", group: "Media", icon: "image", label: "Image", action: insertActions.insertImage },
  {
    id: "embed",
    tab: "insert",
    group: "Media",
    icon: "layout-template",
    label: "Embed",
    modal: openEmbed,
  },
  { id: "table", tab: "insert", group: "Tables", icon: "table", label: "Table", grid: insertActions.insertTableGrid },
  {
    id: "table-insert-row-above",
    tab: "insert",
    group: "Tables",
    icon: INSERT_ROW_ABOVE_ICON,
    label: "Insert Row Above",
    action: tableEdit.insertRowAbove,
    compact: true,
  },
  {
    id: "table-insert-column-left",
    tab: "insert",
    group: "Tables",
    icon: INSERT_COLUMN_LEFT_ICON,
    label: "Insert Column Left",
    action: tableEdit.insertColumnLeft,
    compact: true,
  },
  {
    id: "table-delete-row",
    tab: "insert",
    group: "Tables",
    icon: DELETE_ROW_ICON,
    label: "Delete Row",
    action: tableEdit.deleteRow,
    compact: true,
  },
  {
    id: "table-insert-row-below",
    tab: "insert",
    group: "Tables",
    icon: INSERT_ROW_BELOW_ICON,
    label: "Insert Row Below",
    action: tableEdit.insertRowBelow,
    compact: true,
  },
  {
    id: "table-insert-column-right",
    tab: "insert",
    group: "Tables",
    icon: INSERT_COLUMN_RIGHT_ICON,
    label: "Insert Column Right",
    action: tableEdit.insertColumnRight,
    compact: true,
  },
  {
    id: "table-delete-column",
    tab: "insert",
    group: "Tables",
    icon: DELETE_COLUMN_ICON,
    label: "Delete Column",
    action: tableEdit.deleteColumn,
    compact: true,
  },
  {
    id: "table-align",
    tab: "insert",
    group: "Tables",
    icon: "align-left",
    label: "Align",
    options: [
      { id: "table-align-left", label: "Align Left", action: tableEdit.alignColumnLeft },
      { id: "table-align-center", label: "Align Center", action: tableEdit.alignColumnCenter },
      { id: "table-align-right", label: "Align Right", action: tableEdit.alignColumnRight },
    ],
  },
  {
    id: "code-block",
    tab: "insert",
    group: "Code",
    icon: "square-code",
    label: "Code Block",
    optionColumns: 3,
    optionCellWidth: 120,
    options: CODE_LANGUAGES.map(([fence, label]) => ({
      id: `code-block-${fence || "plain"}`,
      label,
      action: insertActions.insertCodeBlockWithLanguage(fence),
    })),
  },
  {
    id: "horizontal-rule",
    tab: "insert",
    group: "Illustrations",
    icon: "minus",
    label: "Horizontal Rule",
    action: insertActions.insertHorizontalRule,
  },
  {
    id: "callout",
    tab: "insert",
    group: "Illustrations",
    icon: "message-square",
    label: "Callout",
    modal: openCallout,
  },
  {
    id: "symbols",
    tab: "insert",
    group: "Symbols",
    icon: "type",
    label: "Symbols",
    optionColumns: 8,
    options: SYMBOL_OPTIONS,
  },
];
