import type { CommandOption } from "./types";
import * as insertActions from "./actions/insert";

// [id, label, character] for every entry in the Insert > Symbols grid.
const SYMBOLS: [string, string, string][] = [
  ["sym-em-dash", "—  Em Dash", "—"],
  ["sym-en-dash", "–  En Dash", "–"],
  ["sym-ellipsis", "…  Ellipsis", "…"],
  ["sym-nbsp", "Non-breaking Space", " "],
  ["sym-copyright", "©  Copyright", "©"],
  ["sym-registered", "®  Registered", "®"],
  ["sym-trademark", "™  Trademark", "™"],
  ["sym-degree", "°  Degree", "°"],
  ["sym-section", "§  Section", "§"],
  ["sym-paragraph", "¶  Paragraph", "¶"],
  ["sym-bullet", "•  Bullet", "•"],
  ["sym-check", "✓  Checkmark", "✓"],
  ["sym-cross", "✗  Cross", "✗"],
  ["sym-arrow-right", "→  Right Arrow", "→"],
  ["sym-quote-left-double", "“  Left Double Quote", "“"],
  ["sym-quote-right-double", "”  Right Double Quote", "”"],
  ["sym-quote-left-single", "‘  Left Single Quote", "‘"],
  ["sym-quote-right-single", "’  Right Single Quote", "’"],
  ["sym-guillemet-left", "«  Left Guillemet", "«"],
  ["sym-guillemet-right", "»  Right Guillemet", "»"],
  ["sym-dagger", "†  Dagger", "†"],
  ["sym-double-dagger", "‡  Double Dagger", "‡"],
  ["sym-arrow-left", "←  Left Arrow", "←"],
  ["sym-arrow-up", "↑  Up Arrow", "↑"],
  ["sym-arrow-down", "↓  Down Arrow", "↓"],
  ["sym-arrow-both", "↔  Left-Right Arrow", "↔"],
  ["sym-arrow-double-right", "⇒  Right Double Arrow", "⇒"],
  ["sym-arrow-double-both", "⇔  Left-Right Double Arrow", "⇔"],
  ["sym-plus-minus", "±  Plus-Minus", "±"],
  ["sym-multiply", "×  Multiplication", "×"],
  ["sym-divide", "÷  Division", "÷"],
  ["sym-not-equal", "≠  Not Equal", "≠"],
  ["sym-approx", "≈  Approximately Equal", "≈"],
  ["sym-less-equal", "≤  Less Than or Equal", "≤"],
  ["sym-greater-equal", "≥  Greater Than or Equal", "≥"],
  ["sym-infinity", "∞  Infinity", "∞"],
  ["sym-square-root", "√  Square Root", "√"],
  ["sym-micro", "µ  Micro", "µ"],
  ["sym-euro", "€  Euro", "€"],
  ["sym-pound", "£  Pound", "£"],
  ["sym-yen", "¥  Yen", "¥"],
  ["sym-cent", "¢  Cent", "¢"],
  ["sym-star", "★  Star", "★"],
  ["sym-heart", "♥  Heart", "♥"],
  ["sym-warning", "⚠  Warning", "⚠"],
];

export const SYMBOL_OPTIONS: CommandOption[] = SYMBOLS.map(([id, label, character]) => ({
  id,
  label,
  // A non-breaking space is invisible, so show a visible stand-in in the grid.
  display: character === "\u00a0" ? "\u2423" : character,
  action: insertActions.insertSymbol(character),
}));
